#!/bin/bash

while true; do
    read -p "Enter the name of a file: " filename
    if [ -f "$filename" ]; then
        echo "File '$filename' exists."
        break
    else
        echo "File '$filename' does not exist. Please try again."
    fi
done
